### ISSUE TITLE
Demo Proposal: Data Exchange Agreements (eSSIF-Lab)

### ISSUE THREAD

**Issue by lalc** [WebOfTrustInfo/rwot11-the-hague#104]
### Name of Demo
Data Exchange Agreements - Making data transactions trustworthy, auditable and immutable (eSSIF-Lab)

### Demo Details (for titling)
This session provides an end-to-end demo of data exchange agreement protocols during decentralised personal data exchange, using digital wallets and data intermediaries (or MyData Operators).

A Data Disclosure Agreement (DDA) enables automated agreement handling for data exchange between a Data Source (DS) and Data Using Service (DUS). It helps organisations to continue leveraging their data assets while being transparent and legitimate in their data usage. Automated agreement handling is a requisite for a scalable and regulatory-compliant data marketplace. It also provides individuals control over how their data is used and exchanged via Data Agreements.

The demonstration will cover the following: 

1. How any data using service can dynamically signup with a data source within a decentralised ecosystem via data disclosure agreements in a data marketplace or data space
2. How a digital wallet can be used to sign off every data exchange, whether directly between the data source, data using service, or via a digital wallet. 
3. Full auditability of any data exchange via signed agreements 
4. How the individual has full visibility, including data provenance enabled via DEXA (Data Exchange Agreement) protocols. 

This solution is the result of multiple NGI-Trust projects, among others:
1) NGI-Trust ONTOCHAIN: https://ontochain.ngi.eu/content/ps-sda
2) NGI eSSIF-Lab: https://essif-lab.eu/automated-data-agreements-to-simplify-ssi-work-flows-by-igrant-io/

### Name(s) of speakers
Mr. Lal Chandran (iGrant.io)
Mr. Fredrik Linden (MyData Sweden)

### Contact (phone & email)
Phone: +46725298991 
Email: lal@igrant.io

### Name of Company/Project
iGrant.io (Sweden)
MyData (Sweden)

### Content (upload an outline or ppt or something to give us some sense of what we need).
This session uses a laptop with a demo running in our cloud, a digital wallet, a Data Source and a Data Using Service.

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by lalc** [comment]
This will be a real live demo using open source protocols in Aries env.
