### ISSUE TITLE
Demo night proposal: Godiddy.com - Universal DID operations (eSSIF-Lab)

### ISSUE THREAD

**Issue by peacekeeper** [WebOfTrustInfo/rwot11-the-hague#105]
### Name of Demo

Godiddy.com - Universal DID operations (eSSIF-Lab)

### Demo Details (for titling)

Godiddy.com is a product by Danube Tech that makes it easy for developers and solution providers to work with DIDs. It is based on the well-known DIF open-source projects Universal Resolver and Universal Registrar, and adds various advanced DID-related functionality on top of those. This work was funded initially by the eSSIF-Lab Business Open Call 1.

### Name(s) of speakers

Markus Sabadello

### Contact (phone & email)

+43 664 3154848
markus@danubetech.com

### Name of Company/Project

Danube Tech / Godiddy.com

### Content (upload an outline or ppt or something to let us have some sense of what we need).

See here for a longer video demonstration/discussion: https://www.youtube.com/watch?v=Wk5jGJyjBEo

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by peacekeeper** [comment]
Live demo.

**Comment by peacekeeper** [comment]
Just want to add that this is a commercial product, not open-source.. So I would understand if that's not appropriate and other demos get prioritized over this.
