### ISSUE TITLE
Demo Proposal - TNO EASSI - An SSI Wallet Gateway (eSSIF-Lab)

### ISSUE THREAD

**Issue by maaikevanleuken** [WebOfTrustInfo/rwot11-the-hague#106]
### Name of Demo
TNO EASSI - An SSI Wallet Gateway

### Demo Details (for titling)
There are many different SSI wallets, each with their own spin on technological, usability and privacy aspects. In order to ensure autonomy of the holder in choosing their preferred wallet, verifiers and issuers should offer support for a variety of wallets. However, this ordinarily requires quite some manpower, effort and money. TNO EASSI is a solution that allows parties in the role of issuer or verifier to offer support for many wallets to holders by simply connecting to a single gateway. This service facilitates the adoption of SSI by providing an easy to use API, that allows credential issuing and/or verifying organizations to integrate multiple SSI wallets—that may be based on different underlying technologies—with a single interface, taking inspiration from the payment service provider model for online payments.

### Name(s) of speakers
Maaike van Leuken

### Contact (phone & email)
+316 21435173
maaike.vanleuken@tno.nl

### Name of Company/Project
TNO

### Content (upload an outline or ppt or something to let us have some sense of what we need).
I will show a ppt presentation.

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen
