### ISSUE TITLE
eSSIF-Lab TRAIN Demo

### ISSUE THREAD

**Issue by hendersonweb** [WebOfTrustInfo/rwot11-the-hague#107]

**Comment by ChristopherA** [comment]
Can you give more details?

Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by hendersonweb** [comment]
Hi Christopher, ya we have couple of slides and our demo is based with swagger showing couple of API endpoints. That's all we have.

Best Regards,
Isaac Henderson

**Comment by hendersonweb** [comment]
Hi Christopher, ya we have couple of slides and our demo is based with
swagger showing couple of API endpoints. That's all we have.

Best Regards,
Isaac Henderson
