### ISSUE TITLE
Gaia-X Notarisation API

### ISSUE THREAD

**Issue by cstoecker** [WebOfTrustInfo/rwot11-the-hague#111]
### Demo Details (for titling)

* Show Notarisation API workflow and technology
* Explain Gaia-X Federation Services
* Demo eIDAS-bridge integration
* Demo interaction with personal credential manager

### Name(s) of speakers
Konstantin Tsabolov
Carsten Stöcker

### Contact (phone & email)
carsten.stoecker@spherity.com

### Name of Company/Project
Spherity, Gaia-X Federation Service (GXFS) Example.

### Content (upload an outline or ppt or something to let us have some sense of what we need).

The purpose of the Notarisation API is to attest given master data and transform it to W3C compliant digital Verifiable Credential representation. 

These made tamper-proof digital claims about certain attributes are central to gain the desired trust in any provided self-descriptions of assets and participants in the distributed GAIA-X ecosystem. 

Examples of verification and digital attestation are:
* transform classic certificates of any 3rd party certifier to digital verifiable credential formats with desired signatures
* GAIA-X participants and associated master data (e.g., address, name, tax identification number etc.)
* ownership of the given organization DID – relates it to the real verified organization
* business owner (e.g., by eID) to bridge SSI with eIDAS regulations
* Organizations acting as trust anchor. E.g., Governments, Gaia-X AISBL, etc.

The Notarisation API composes of an eIDAS bridge, notarisation API roles and process flows well as an integration of AIP 1.0 and 2.0. 

The demo will also show the GXFS implementation of the Personal Credential Manager (Human Edge Wallet).

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen
