### ISSUE TITLE
Verifiable Credential Issuer Playground

### ISSUE THREAD

**Issue by msporny** [WebOfTrustInfo/rwot11-the-hague#112]
### Name of Demo

Verifiable Credential Issuer Playground

### Demo Details (for titling)

A demonstration of Verifiable Credential issuance, open wallet selection, and storage in a digital wallet.

### Name(s) of speakers

Manu Sporny

### Contact (phone & email)

phone: Not willing to provide in a public setting -- RWoT leadership has my phone number
email: msporny@digitalbazaar.com

### Name of Company/Project

Digital Bazaar

### Content (upload an outline or ppt or something to let us have some sense of what we need).

* An overview of technologies used will be provided (depending on time allocation)
  * Verifiable Credentials: https://www.w3.org/TR/vc-data-model/
  * Data Integrity: https://w3c.github.io/vc-data-integrity/
  * Credential Handler API: https://github.com/credential-handler/credential-handler-polyfill
  * Verifiable Presentation Request: https://w3c-ccg.github.io/vp-request-spec/
  * Verifiable Credential API: https://chapi.io/
* A demonstration of picking up various types of Verifiable Credentials into a digital wallet will be provided
  * https://playground.chapi.io/issuer

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by msporny** [comment]
This will be a real live demo.
