### ISSUE TITLE
[Demo Proposal] DID Connect live demo

### ISSUE THREAD

**Issue by mave99a** [WebOfTrustInfo/rwot11-the-hague#119]
### Name of Demo

 DID Connect live demo

### Demo Details (for titling)

This is a live demo for DID Connect (https://github.com/WebOfTrustInfo/rwot11-the-hague/blob/master/advance-readings/did-connect.md) 

DID Connect is a suite of RESTful APIs, UX components and SDK that provide a framework for DID interactions, connecting people, devices and applications via DID and Verifiable Credentials. DID Connect allows for clients of all types including browser-based, mobile, and javascript clients, to request and receive information about identities and the presentation of Verifiable Credentials. DID Connect focuses on the end users experience and applications, it’s independent to specific DID method implementations.

The demo is performance with a browser with a playground applications on the cloud and a mobile digital wallet. 

### Name(s) of speakers

Robert Mao 

### Contact (phone & email)

+1 425 4425101
rob@arcblock.io

### Name of Company/Project

ArcBlock, Inc.  / DID Connect  (United States)

### Content (upload an outline or ppt or something to let us have some sense of what we need).

This session uses a browser with a demo running in our cloud, a digital wallet (https://didwallet.io).  The demo is interactive, audience can participate with a downloaded digital wallet.

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by mave99a** [comment]
It's a live demo. no PPT
