### ISSUE TITLE
[Demo Proposal] DID Science; global DID data analyses

### ISSUE THREAD

**Issue by zaida-rivai** [WebOfTrustInfo/rwot11-the-hague#121]
### Name of Demo

DID Science; global DID data analyses

### Demo Details (for titling)

* A presentation of analyses on global DID data. 
* Graphs and figures on the distribution of several DIDs over time 
* Overview of different errors occurring in DIDs 
* Distribution of different verification method key types 

### Name(s) of speakers

Zaida Rivai 
(Markus Sabadello)

### Contact

zaida.rivai@danubetech.com

### Name of Company/Project

Danube Tech GmbH (Austria)

### Content (upload an outline or ppt or something to let us have some sense of what we need).

This session uses a powerpoint presentation only. There is no browser needed.

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by zaida-rivai** [comment]
This will be slides, Unfortunately i don't have a demo, graphs only.

Op di 27 sep. 2022 19:11 schreef Christopher Allen ***@***.***
