### ISSUE TITLE
[Demo Proposal] Visual Hash - Applying image hashing technology to verifiable credentials 

### ISSUE THREAD

**Issue by victormartinez-work** [WebOfTrustInfo/rwot11-the-hague#134]
### Name of Demo

Visual Hash - Applying image hashing technology to verifiable credentials 

### Demo Details (for titling)

![image](https://user-images.githubusercontent.com/69150249/192044782-ad5f7429-6f0d-4f7c-8405-7299c51634f9.png)

Visual hash is an image authentication technology that combines image hashing and machine learning techniques.  
This technology has been designed to work nicely in combination with  Verifiable credentials . It solves the problem of adding images in Verifiable credentials in a privacy-preserving, offline and inclusive way.  

### Name(s) of speakers
Víctor Martínez Jurado
Andrew Slack

### Contact (phone & email)
victor.martinez@sicpa.com
andrew.slack@sicpa.com

### Name of Company/Project
SICPA

### Content (upload an outline or ppt or something to let us have some sense of what we need).

We will be using a slide deck + a real demo with physical samples and a demo app (iPhone)

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by victormartinez-work** [comment]
Will be a live demo + couple slides
