### ISSUE TITLE
[Demo Proposal] Trusted Crypto Asset

### ISSUE THREAD

**Issue by elenachachkarova** [WebOfTrustInfo/rwot11-the-hague#135]
### Name of Demo
Trusted Crypto Asset framework - [NYMLAB srl](https://www.nymlab.it/)

### Demo Details (for titling)
Trusted Crypto Asset framework is developed by NYMLAB team and presents a way for issuers and holders to create/use a regulated asset in the context of a permissioned public decentralised network, leveraging on SSI protocols. We define a “Trusted Crypto Asset” as a particular asset class that intends to anticipate and satisfy regulatory requirements regarding the asset issuers, the network where they are minted and their holders.

### Name(s) of speakers
[Belsy Yuen](mailto:belsy@nymlab.it)

### Contact (phone & email)
[belsy@nymlab.it](mailto:belsy@nymlab.it)

### Name of Company/Project
[NYMLAB srl ](https://www.nymlab.it/)/ [Trusted Crypto Asset](https://github.com/nymlab/trusted-crypto-asset)

### Content (upload an outline or ppt or something to let us have some sense of what we need).
We will be using a slide deck. [Here](https://youtu.be/ZqQdtupe9bc) is a link to a version of the demo we recently gave at one of our [Discord](https://discord.gg/hdvZREHz) community meetings.

**Comment by ChristopherA** [comment]
Will this be a demo or slides? We are prioritizing real live demos for 5 minutes over slide presentations.

— Christopher Allen

**Comment by egidiocasati** [comment]
Thanks, it's a Live Demo
