### ISSUE TITLE
PR#11 now has merging conflicts

### ISSUE THREAD

**Issue by RieksJ** [WebOfTrustInfo/rwot11-the-hague#14]
When I created [PR#11](https://github.com/WebOfTrustInfo/rwot11-the-hague/pull/11), everything was ok - it said it could be merged. 
When I look now, there are conflicts (in the README file, where Oliver Terbu appears to have added his contribution).
My Git-capabilities are not that evolved that I know how to resolve those.
Can anyone help out?

**Comment by elenachachkarova** [comment]
No problem at all, should be all merged now. You will receive an email with a promo code soon. Thank you for submitting your paper again.
