### ISSUE TITLE
Update repo name from netherlands to the hague

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/rwot11-the-hague#3]
Since all other rwot's have been a city rather than a country we decided it best to stick to this pattern.

Chris also asked me to remind you about changing to rwot11 first then to rwot11-the-hague because of how Github handles redirects.

**Comment by shannona** [comment]
Done (and I've verified the plain 'rwot11' still works, thanks to the redirect trick).

I'll in turn remind that there are some links to the repo in the Eventbrite that will now need to be updated.
